name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  validity:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check source is valid
        run: cargo check

  tests:
    needs: validity

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Run tests
        run: cargo test --verbose

  formating:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Check formatting with rustfmt
        run: cargo fmt --all -- --check
